import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { DataProvider } from "../context/DataContext";
import { UserProvider } from "../context/UserContext";
import ReactQueryProvider from "../providers/ReactQueryProvider"; // Adjust path if needed
import { ApolloWrapper } from "@/lib/ApolloWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <DataProvider>
              <UserProvider>
                <ReactQueryProvider>{children}</ReactQueryProvider>
              </UserProvider>
            </DataProvider>
          </ThemeProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
