/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cop.glb 
Author: temich (https://sketchfab.com/temich_)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dodge-charger-srt-police-c6d52512e32d42abb89466ced4d56c1d
Title: DODGE CHARGER SRT (POLICE)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cop(props) {
  const { nodes, materials } = useGLTF('/models/cop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.138, 14.556, -11.689]} scale={55.68}>
          <group position={[0.473, 0.972, 0.566]} rotation={[0.175, 0, 0]}>
            <mesh geometry={nodes.tahook_SUB0001_Plastic_int_0.geometry} material={materials.Plastic_int} />
            <mesh geometry={nodes.tahook_SUB1001_red1_int_0.geometry} material={materials.red1_int} />
          </group>
          <group position={[0.3, 0.972, 0.566]} rotation={[0.175, 0, 0]}>
            <mesh geometry={nodes.speedo_SUB0001_Plastic_int_0.geometry} material={materials.Plastic_int} />
            <mesh geometry={nodes.speedo_SUB1001_red1_int_0.geometry} material={materials.red1_int} />
          </group>
          <group position={[0, 1.108, -1.721]} rotation={[-Math.PI, 0, -Math.PI]}>
            <group position={[0, 0, 0.122]} rotation={[-Math.PI / 2, 0, Math.PI]}>
              <mesh geometry={nodes.boot003_frame_0.geometry} material={materials.frame} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.boot005_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.boot001_frame_0.geometry} material={materials.frame} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.boot_redeye001_EXT_Redeye_0.geometry} material={materials.EXT_Redeye} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh geometry={nodes.boot_spoiler001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} position={[0, 0, 0.034]} />
              </group>
              <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
                <mesh geometry={nodes.misc_c009_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} position={[0.005, -0.21, 0.603]} />
              </group>
              <mesh geometry={nodes.misc_c001_black_30_percent_alpha_0.geometry} material={materials.black_30_percent_alpha} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.misc_c008_frame_0.geometry} material={materials.frame} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.misc_c004_Glass_0.geometry} material={materials.Glass} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.misc_c002_red_80_percent_alpha_0.geometry} material={materials.red_80_percent_alpha} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.misc_c_light_misc001_t_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.misc_c_light_reversing_low001_t_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.misc_d001_Glass_0.geometry} material={materials.Glass} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.reversinglight001_t_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.taillight001_light1_0.geometry} material={materials.light1} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh geometry={nodes.boot_SUB0001_SKIN_01_0.geometry} material={materials.SKIN_01} />
              <mesh geometry={nodes.boot_SUB1001_EXT_Chrome_0.geometry} material={materials.EXT_Chrome} />
              <mesh geometry={nodes.boot_SUB2001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
              <mesh geometry={nodes.boot_SUB3001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
              <mesh geometry={nodes.boot_SUB4001_INT_carpet_black_dif_0.geometry} material={materials.INT_carpet_black_dif} />
            </group>
          </group>
          <group position={[0, 1.017, 0.978]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.bonnet001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} position={[0, 0, 0.002]} />
            <mesh geometry={nodes.bonnet004_emergrx_0.geometry} material={materials.emergrx} />
            <mesh geometry={nodes.bonnet005_emergrx_0.geometry} material={materials.emergrx} />
            <mesh geometry={nodes.bonnet006_emergrx_0.geometry} material={materials.emergrx} />
            <mesh geometry={nodes.bonnet_SUB2001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} position={[0, 0, 0.002]} />
            <mesh geometry={nodes.bonnet_SUB3001_EXT_grillepl1_0.geometry} material={materials.EXT_grillepl1} position={[0, 0, 0.002]} />
            <mesh geometry={nodes.bonnet_SUB4001_frame_0.geometry} material={materials.frame} />
          </group>
          <group position={[0.902, 0.68, 0.812]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.window_lf_ext001_EXT_Glass_0.geometry} material={materials.EXT_Glass} position={[-0.172, 0.703, 0.505]} />
            <mesh geometry={nodes.window_lf_int001_INTERNAL_glass_0.geometry} material={materials.INTERNAL_glass} position={[-0.172, 0.703, 0.505]} />
            <mesh geometry={nodes.door_lf001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            <mesh geometry={nodes.door_lf003_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.door_lf_SUB0001_dod_chargersrthellcat_15_doortags_diff_int_alpha_0.geometry} material={materials.dod_chargersrthellcat_15_doortags_diff_int_alpha} />
            <mesh geometry={nodes.door_lf_SUB1001_key_hole_002_ext_0.geometry} material={materials.key_hole_002_ext} />
            <mesh geometry={nodes.door_lf_SUB10001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.door_lf_SUB11001_INT_Chrome_0.geometry} material={materials.INT_Chrome} />
            <mesh geometry={nodes.door_lf_SUB12001_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} />
            <mesh geometry={nodes.door_lf_SUB13001_INT_Plastic_Slush_blk_DIF_0.geometry} material={materials.INT_Plastic_Slush_blk_DIF} />
            <mesh geometry={nodes.door_lf_SUB14001_INT_moket2_third_paint_0.geometry} material={materials.INT_moket2_third_paint} />
            <mesh geometry={nodes.door_lf_SUB15001_INT_speaker_diff_0.geometry} material={materials.INT_speaker_diff} />
            <mesh geometry={nodes.door_lf_SUB16001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
            <mesh geometry={nodes.door_lf_SUB2001_stitch_003_glos_int_third_paint_0.geometry} material={materials.stitch_003_glos_int_third_paint} />
            <mesh geometry={nodes.door_lf_SUB3001_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.door_lf_SUB4001_dod_chargersrthellcat_15_symbols_diff_int_alpha_lit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_lit} />
            <mesh geometry={nodes.door_lf_SUB5001_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.door_lf_SUB6001_SKIN_01_0.geometry} material={materials.SKIN_01} />
            <mesh geometry={nodes.door_lf_SUB7001_INTEXT_Plastic_0.geometry} material={materials.INTEXT_Plastic} />
            <mesh geometry={nodes.door_lf_SUB8001_INTEXT_Chrome_0.geometry} material={materials.INTEXT_Chrome} />
            <mesh geometry={nodes.door_lf_SUB9001_EXT_Rubber_0.geometry} material={materials.EXT_Rubber} />
            <mesh geometry={nodes.door_lf_mirror001_Mirror_0.geometry} material={materials.Mirror} />
          </group>
          <group position={[0.91, 0.68, -0.324]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.window_lr_ext001_EXT_Glass_0.geometry} material={materials.EXT_Glass} position={[-0.181, 0.515, 0.514]} />
            <mesh geometry={nodes.window_lr_int001_INTERNAL_glass_0.geometry} material={materials.INTERNAL_glass} position={[-0.181, 0.515, 0.514]} />
            <mesh geometry={nodes.door_lr_SUB0001_stitch_003_glos_int_third_paint_0.geometry} material={materials.stitch_003_glos_int_third_paint} />
            <mesh geometry={nodes.door_lr_SUB1001_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.door_lr_SUB10001_INT_moket2_third_paint_0.geometry} material={materials.INT_moket2_third_paint} />
            <mesh geometry={nodes.door_lr_SUB11001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
            <mesh geometry={nodes.door_lr_SUB12001_INT_Chrome_0.geometry} material={materials.INT_Chrome} />
            <mesh geometry={nodes.door_lr_SUB13001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            <mesh geometry={nodes.door_lr_SUB2001_dod_chargersrthellcat_15_symbols_diff_int_alpha_lit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_lit} />
            <mesh geometry={nodes.door_lr_SUB3001_SKIN_01_0.geometry} material={materials.SKIN_01} />
            <mesh geometry={nodes.door_lr_SUB4001_INTEXT_Chrome_0.geometry} material={materials.INTEXT_Chrome} />
            <mesh geometry={nodes.door_lr_SUB5001_INTEXT_Plastic_0.geometry} material={materials.INTEXT_Plastic} />
            <mesh geometry={nodes.door_lr_SUB6001_EXT_Rubber_0.geometry} material={materials.EXT_Rubber} />
            <mesh geometry={nodes.door_lr_SUB7001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.door_lr_SUB8001_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} />
            <mesh geometry={nodes.door_lr_SUB9001_INT_Plastic_Slush_blk_DIF_0.geometry} material={materials.INT_Plastic_Slush_blk_DIF} />
          </group>
          <group position={[-0.902, 0.68, 0.812]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.window_rf_ext001_EXT_Glass_0.geometry} material={materials.EXT_Glass} position={[0.172, 0.703, 0.505]} />
            <mesh geometry={nodes.window_rf_int001_INTERNAL_glass_0.geometry} material={materials.INTERNAL_glass} position={[0.172, 0.703, 0.505]} />
            <mesh geometry={nodes.door_rf002_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            <mesh geometry={nodes.door_rf_SUB0001_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.door_rf_SUB1001_stitch_003_glos_int_third_paint_0.geometry} material={materials.stitch_003_glos_int_third_paint} />
            <mesh geometry={nodes.door_rf_SUB10001_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} />
            <mesh geometry={nodes.door_rf_SUB11001_INT_Plastic_Slush_blk_DIF_0.geometry} material={materials.INT_Plastic_Slush_blk_DIF} />
            <mesh geometry={nodes.door_rf_SUB12001_INT_moket2_third_paint_0.geometry} material={materials.INT_moket2_third_paint} />
            <mesh geometry={nodes.door_rf_SUB13001_INT_speaker_diff_0.geometry} material={materials.INT_speaker_diff} />
            <mesh geometry={nodes.door_rf_SUB14001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
            <mesh geometry={nodes.door_rf_SUB2001_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.door_rf_SUB3001_dod_chargersrthellcat_15_symbols_diff_int_alpha_lit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_lit} />
            <mesh geometry={nodes.door_rf_SUB4001_SKIN_01_0.geometry} material={materials.SKIN_01} />
            <mesh geometry={nodes.door_rf_SUB5001_INTEXT_Plastic_0.geometry} material={materials.INTEXT_Plastic} />
            <mesh geometry={nodes.door_rf_SUB6001_INTEXT_Chrome_0.geometry} material={materials.INTEXT_Chrome} />
            <mesh geometry={nodes.door_rf_SUB7001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.door_rf_SUB8001_EXT_Rubber_0.geometry} material={materials.EXT_Rubber} />
            <mesh geometry={nodes.door_rf_SUB9001_INT_Chrome_0.geometry} material={materials.INT_Chrome} />
            <mesh geometry={nodes.door_rf_mirror001_Mirror_0.geometry} material={materials.Mirror} />
          </group>
          <group position={[-0.91, 0.68, -0.324]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.window_rr_ext001_EXT_Glass_0.geometry} material={materials.EXT_Glass} position={[0.182, 0.515, 0.514]} />
            <mesh geometry={nodes.window_rr_int001_INTERNAL_glass_0.geometry} material={materials.INTERNAL_glass} position={[0.182, 0.515, 0.514]} />
            <mesh geometry={nodes.door_rr_SUB0001_dod_chargersrthellcat_15_symbols_diff_int_alpha_lit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_lit} />
            <mesh geometry={nodes.door_rr_SUB1001_stitch_003_glos_int_third_paint_0.geometry} material={materials.stitch_003_glos_int_third_paint} />
            <mesh geometry={nodes.door_rr_SUB10001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
            <mesh geometry={nodes.door_rr_SUB11001_INT_moket2_third_paint_0.geometry} material={materials.INT_moket2_third_paint} />
            <mesh geometry={nodes.door_rr_SUB12001_INT_Chrome_0.geometry} material={materials.INT_Chrome} />
            <mesh geometry={nodes.door_rr_SUB13001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            <mesh geometry={nodes.door_rr_SUB2001_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.door_rr_SUB3001_SKIN_01_0.geometry} material={materials.SKIN_01} />
            <mesh geometry={nodes.door_rr_SUB4001_INTEXT_Chrome_0.geometry} material={materials.INTEXT_Chrome} />
            <mesh geometry={nodes.door_rr_SUB5001_INTEXT_Plastic_0.geometry} material={materials.INTEXT_Plastic} />
            <mesh geometry={nodes.door_rr_SUB6001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.door_rr_SUB7001_EXT_Rubber_0.geometry} material={materials.EXT_Rubber} />
            <mesh geometry={nodes.door_rr_SUB8001_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} />
            <mesh geometry={nodes.door_rr_SUB9001_INT_Plastic_Slush_blk_DIF_0.geometry} material={materials.INT_Plastic_Slush_blk_DIF} />
          </group>
          <group position={[0, 0.687, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.chassis_navigation_screen001_Navigation_0.geometry} material={materials.Navigation} position={[-0.012, -0.543, 0.24]} />
            <mesh geometry={nodes['chassis_permforance_screen001_tech-slide-5_lit_0'].geometry} material={materials['tech-slide-5_lit']} position={[-0.012, -0.535, 0.24]} />
          </group>
          <group position={[0.386, 0.881, 0.375]} rotation={[0.384, 0, 0]} scale={0.872}>
            <group scale={1.146}>
              <mesh geometry={nodes.steeringwheel001_SUB0001_dod_chargersrthellcat_15_symbols_embossed_opac_int_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_embossed_opac_int} />
              <mesh geometry={nodes.steeringwheel001_SUB1001_stitch_00101_diff_int_0.geometry} material={materials.stitch_00101_diff_int} />
              <mesh geometry={nodes.steeringwheel001_SUB2001_srt_02_int_0.geometry} material={materials.srt_02_int} />
              <mesh geometry={nodes.steeringwheel001_SUB3001_dod_chargersrthellcat_15_symbols_diff_int_alpha_lit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_lit} />
              <mesh geometry={nodes.steeringwheel_SUB0001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
              <mesh geometry={nodes.steeringwheel_SUB1001_INT_Leather_Perforatedb_0.geometry} material={materials.INT_Leather_Perforatedb} />
              <mesh geometry={nodes.steeringwheel_SUB2001_INT_Plastic_Slush_blk_DIF_0.geometry} material={materials.INT_Plastic_Slush_blk_DIF} />
              <mesh geometry={nodes.steeringwheel_SUB3001_INT_Chrome_matte_0.geometry} material={materials.INT_Chrome_matte} />
              <mesh geometry={nodes.steeringwheel_SUB4001_INT_plastic_leather_blk_0.geometry} material={materials.INT_plastic_leather_blk} />
              <mesh geometry={nodes.steeringwheel_SUB5001_INT_Chrome_0.geometry} material={materials.INT_Chrome} />
            </group>
          </group>
          <group position={[0.655, 0.961, 1.063]} rotation={[-1.399, 0.261, 0.023]}>
            <mesh geometry={nodes.wipers_left001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.wipers_left_base001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
          </group>
          <group position={[0.044, 0.979, 1.201]} rotation={[-0.96, 0.07, 0]}>
            <mesh geometry={nodes.wipers_right001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.wipers_right_base001_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
          </group>
          <group position={[0, 0.687, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.brakelight_l001_tailred_0.geometry} material={materials.tailred} position={[0.65, 2.35, 0.221]} />
            <mesh geometry={nodes.brakelight_m001_tailred_0.geometry} material={materials.tailred} position={[0, 1.135, 0.685]} />
            <mesh geometry={nodes.brakelight_r001_tailred_0.geometry} material={materials.tailred} position={[-0.65, 2.35, 0.221]} />
            <group position={[-0.803, -1.991, 0.034]}>
              <mesh geometry={nodes.bumper_f012_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} position={[1.606, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
              <group position={[1.606, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI]}>
                <mesh geometry={nodes.bumper_f016_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
                <mesh geometry={nodes.bumper_f017_vehiclelights128_0.geometry} material={materials.vehiclelights128} />
                <mesh geometry={nodes.bumper_f018_vehiclelights128_0.geometry} material={materials.vehiclelights128} />
              </group>
              <mesh geometry={nodes.bumper_f_glass001_Glass_0.geometry} material={materials.Glass} position={[1.606, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
              <mesh geometry={nodes.bumper_f_sides_light001_indi_0.geometry} material={materials.indi} position={[1.606, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
              <mesh geometry={nodes.bumper_f_sides_light_nolit001_indi_0.geometry} material={materials.indi} position={[1.606, 0, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
              <mesh geometry={nodes.dtr_light_glass001_Glass_0.geometry} material={materials.Glass} position={[0.803, -0.058, 0.017]} />
              <mesh geometry={nodes.glass_light_f001_Glass_0.geometry} material={materials.Glass} position={[0.803, -0.058, 0.017]} />
              <group position={[0.803, -0.309, -0.021]}>
                <mesh geometry={nodes.grille002_frame_0.geometry} material={materials.frame} position={[0, 0.033, 0]} />
              </group>
              <mesh geometry={nodes.headlight_l001_light_0.geometry} material={materials.light} position={[1.544, -0.07, 0.005]} />
              <mesh geometry={nodes.headlight_r001_light_0.geometry} material={materials.light} position={[0.063, -0.07, 0.005]} />
              <mesh geometry={nodes.light_front_glass001_Glass_0.geometry} material={materials.Glass} position={[0.803, -0.058, 0.017]} />
              <mesh geometry={nodes.lights_dtr001_t_0.geometry} material={materials.material} position={[0.803, -0.058, 0.017]} />
              <mesh geometry={nodes.lights_ind_l_f001_Headlight_Reflector_0.geometry} material={materials.Headlight_Reflector} position={[0.803, -0.058, 0.017]} />
              <mesh geometry={nodes.lights_ind_r_f001_Headlight_Reflector_0.geometry} material={materials.Headlight_Reflector} position={[0.803, -0.058, 0.017]} />
              <mesh geometry={nodes.misc_e001_frame_0.geometry} material={materials.frame} position={[0.803, -0.058, 0.017]} />
              <mesh geometry={nodes.bumper_f002_frame_0.geometry} material={materials.frame} />
              <mesh geometry={nodes.bumper_f008_EXT_Plastic_env_0.geometry} material={materials.EXT_Plastic_env} />
              <mesh geometry={nodes.bumper_f004_EXT_Red_0.geometry} material={materials.EXT_Red} />
              <mesh geometry={nodes.bumper_f003_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
              <mesh geometry={nodes.bumper_f010_EXT_Chrome_0.geometry} material={materials.EXT_Chrome} position={[0.977, -0.144, 0.015]} />
              <mesh geometry={nodes.bumper_f014_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
              <mesh geometry={nodes.bumper_f_redeye001_EXT_Redeye_0.geometry} material={materials.EXT_Redeye} />
            </group>
            <group position={[0.882, 1.808, 0.019]}>
              <mesh geometry={nodes.bumper_r008_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} rotation={[-Math.PI / 2, 0, Math.PI]} />
              <mesh geometry={nodes.bumper_r002_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
              <mesh geometry={nodes.bumper_r004_EXT_grillepl1_0.geometry} material={materials.EXT_grillepl1} />
              <mesh geometry={nodes.bumper_r006_frame_0.geometry} material={materials.frame} />
              <mesh geometry={nodes.bumper_r_glass001_Glass_0.geometry} material={materials.Glass} />
              <mesh geometry={nodes.bumper_r_plate_light001_t_0.geometry} material={materials.material} />
              <mesh geometry={nodes.bumper_r_side_lights001_tailred_0.geometry} material={materials.tailred} />
              <mesh geometry={nodes.bumper_r_side_lights_nolit001_tailred_0.geometry} material={materials.tailred} />
            </group>
            <group position={[0, -1.63, 0.106]}>
              <mesh geometry={nodes.exhaust_SUB0001_frame_0.geometry} material={materials.frame} position={[0, 4.112, -0.53]} />
              <mesh geometry={nodes.exhaust_SUB1001_EXT_Chrome_exh_0.geometry} material={materials.EXT_Chrome_exh} />
            </group>
            <group position={[0, -1.401, -0.113]}>
              <mesh geometry={nodes.fenders_SUB0001_frame_0.geometry} material={materials.frame} />
              <mesh geometry={nodes.fenders_SUB1001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            </group>
            <mesh geometry={nodes.gauges_airbag001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_base001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_brake001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_dashscreen001_dod_chargerfast7_15_tach_graphics_0.geometry} material={materials.dod_chargerfast7_15_tach_graphics} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_engine001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_fog_light001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_fullbeam001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_handbrake001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_ind_left001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_ind_right001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_main001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_main_lit001_dod_chargersrthellcat_15_gauges_lite_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_lite} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_parking001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_seatbelt001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_side_lights001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_tcs001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.gauges_tcs_off001_dod_chargersrthellcat_15_gauges_diff_0.geometry} material={materials.dod_chargersrthellcat_15_gauges_diff} position={[0.389, -0.571, 0.289]} />
            <mesh geometry={nodes.light_rear_glass001_Glass_0.geometry} material={materials.Glass} position={[0, 2.499, 0.239]} />
            <mesh geometry={nodes.light_rear_glass_black001_black_30_percent_alpha_0.geometry} material={materials.black_30_percent_alpha} position={[0, 2.499, 0.239]} />
            <mesh geometry={nodes.light_rear_glass_red001_red_80_percent_alpha_0.geometry} material={materials.red_80_percent_alpha} position={[0, 2.499, 0.239]} />
            <mesh geometry={nodes.light_rear_tail001_light1_0.geometry} material={materials.light1} position={[0.751, 2.35, 0.19]} />
            <mesh geometry={nodes.misc_a001_frame_0.geometry} material={materials.frame} position={[0, 2.499, 0.239]} />
            <mesh geometry={nodes.misc_a003_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} position={[0, 2.499, 0.239]} />
            <mesh geometry={nodes.misc_a005_tailred003_0.geometry} material={materials['tailred.003']} position={[0, 2.499, 0.239]} />
            <group position={[0, -0.001, -0.476]}>
              <mesh geometry={nodes.sideskirt_SUB0001_frame_0.geometry} material={materials.frame} />
              <mesh geometry={nodes.sideskirt_SUB1001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            </group>
            <mesh geometry={nodes.suspension_lf_LOD1001_MET_1_0.geometry} material={materials.MET_1} position={[0.422, -1.567, -0.232]} />
            <mesh geometry={nodes.suspension_lr_LOD1001_MET_1_0.geometry} material={materials.MET_1} position={[0.487, 1.436, -0.31]} />
            <mesh geometry={nodes.suspension_rf_LOD1001_MET_1_0.geometry} material={materials.MET_1} position={[-0.422, -1.567, -0.232]} />
            <mesh geometry={nodes.suspension_rr_LOD1001_MET_1_0.geometry} material={materials.MET_1} position={[-0.487, 1.436, -0.31]} />
            <mesh geometry={nodes.windscreen_ext001_EXT_Glass_0.geometry} material={materials.EXT_Glass} position={[0, -0.699, 0.499]} />
            <mesh geometry={nodes.windscreen_r_ext001_EXT_Glass_0.geometry} material={materials.EXT_Glass} position={[0, 1.518, 0.548]} />
            <group position={[0, 1.518, 0.548]}>
              <mesh geometry={nodes.windscreen_r_int002_INTERNAL_glass_0.geometry} material={materials.INTERNAL_glass} />
              <mesh geometry={nodes.windscreen_r_lines001_defrostlines_002_opac_0.geometry} material={materials.defrostlines_002_opac} />
            </group>
            <mesh geometry={nodes.bodyshell_SUB0001_CHROME_0.geometry} material={materials.CHROME} />
            <mesh geometry={nodes.bodyshell_SUB1001_dod_chargersrthellcat_15_doortags_diff_alpha_0.geometry} material={materials.dod_chargersrthellcat_15_doortags_diff_alpha} />
            <mesh geometry={nodes.bodyshell_SUB2001_BLACK_BODY_0.geometry} material={materials.BLACK_BODY} />
            <mesh geometry={nodes.bodyshell_SUB3001_frame_0.geometry} material={materials.frame} />
            <mesh geometry={nodes.bodyshell_SUB4001_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.bodyshell_SUB5001_SKIN_01_0.geometry} material={materials.SKIN_01} />
            <mesh geometry={nodes.bodyshell_SUB6001_EXT_Rubber_0.geometry} material={materials.EXT_Rubber} />
            <mesh geometry={nodes.bodyshell_SUB7001_EXT_Black_Glass_0.geometry} material={materials.EXT_Black_Glass} />
            <mesh geometry={nodes.bodyshell_SUB8001_EXT_Chrome_hellcat_0.geometry} material={materials.EXT_Chrome_hellcat} />
            <mesh geometry={nodes.bodyshell_SUB9001_CAR_PAINT_0.geometry} material={materials.CAR_PAINT} />
            <mesh geometry={nodes.bodyshell_SUB9002_EXT_Plastic_0.geometry} material={materials.EXT_Plastic} />
            <mesh geometry={nodes.bodyshell_intext_SUB0001_INTEXT_Chrome_0.geometry} material={materials.INTEXT_Chrome} />
            <mesh geometry={nodes.bodyshell_intext_SUB1001_INTEXT_Plastic_0.geometry} material={materials.INTEXT_Plastic} />
            <mesh geometry={nodes.bodyshell_redeye001_EXT_Redeye_0.geometry} material={materials.EXT_Redeye} />
            <mesh geometry={nodes.chassis_SUB0001_srt_008_0.geometry} material={materials.srt_008} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB1001_en_ridges_002b_nrml_0.geometry} material={materials.en_ridges_002b_nrml} />
            <mesh geometry={nodes.chassis_SUB10001_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} />
            <mesh geometry={nodes.chassis_SUB10002_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB10003_INT_plastic_leather_wht_diff_secondary_paint_0.geometry} material={materials.INT_plastic_leather_wht_diff_secondary_paint} />
            <mesh geometry={nodes.chassis_SUB11001_INT_plastic_leather_blk_0.geometry} material={materials.INT_plastic_leather_blk} />
            <mesh geometry={nodes.chassis_SUB12001_INT_carbon_fiber_0.geometry} material={materials.INT_carbon_fiber} />
            <mesh geometry={nodes.chassis_SUB13001_INT_Plastic_ridges_008b_nrml001_0.geometry} material={materials['INT_Plastic_ridges_008b_nrml.001']} />
            <mesh geometry={nodes.chassis_SUB14001_INT_Plastic_Slush_blk_DIF_0.geometry} material={materials.INT_Plastic_Slush_blk_DIF} />
            <mesh geometry={nodes.chassis_SUB15001_INT_Plastic_ridges_008b_nrml_0.geometry} material={materials.INT_Plastic_ridges_008b_nrml} />
            <mesh geometry={nodes.chassis_SUB16001_INT_Chrome_0.geometry} material={materials.INT_Chrome} />
            <mesh geometry={nodes.chassis_SUB16002_INT_Chrome_0.geometry} material={materials.INT_Chrome} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB17001_INT_Plastic_Env_0.geometry} material={materials.INT_Plastic_Env} />
            <mesh geometry={nodes.chassis_SUB17002_INT_Plastic_Env_0.geometry} material={materials.INT_Plastic_Env} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB18001_INT_red1_0.geometry} material={materials.INT_red1} />
            <mesh geometry={nodes.chassis_SUB19001_INT_carpet_black_dif_0.geometry} material={materials.INT_carpet_black_dif} />
            <mesh geometry={nodes.chassis_SUB2001_frame_0.geometry} material={materials.frame} />
            <mesh geometry={nodes.chassis_SUB2003_frame_0.geometry} material={materials.frame} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB20001_INT_fabric_roof_nr_0.geometry} material={materials.INT_fabric_roof_nr} />
            <mesh geometry={nodes.chassis_SUB21001_INT_belt_d_0.geometry} material={materials.INT_belt_d} />
            <mesh geometry={nodes.chassis_SUB22001_INT_alcnt_0.geometry} material={materials.INT_alcnt} />
            <mesh geometry={nodes.chassis_SUB23001_INT_moket2_third_paint_0.geometry} material={materials.INT_moket2_third_paint} />
            <mesh geometry={nodes.chassis_SUB23002_INT_moket2_third_paint_0.geometry} material={materials.INT_moket2_third_paint} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB24001_INT_leather_perforated_third_paint_0.geometry} material={materials.INT_leather_perforated_third_paint} />
            <mesh geometry={nodes.chassis_SUB24002_INT_leather_perforated_third_paint_0.geometry} material={materials.INT_leather_perforated_third_paint} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB25001_INT_speaker_diff_0.geometry} material={materials.INT_speaker_diff} />
            <mesh geometry={nodes.chassis_SUB26001_INT_Plastic_NM_0.geometry} material={materials.INT_Plastic_NM} />
            <mesh geometry={nodes.chassis_SUB26002_INT_Plastic_NM_0.geometry} material={materials.INT_Plastic_NM} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB27001_dod_chargersrthellcat_15_symbols_diff_int_alpha_lit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_lit} />
            <mesh geometry={nodes.chassis_SUB28001_dod_chargersrthellcat_15_symbols_diff_int_alpha_nolit_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_diff_int_alpha_nolit} />
            <mesh geometry={nodes.chassis_SUB3001_dod_chargersrthellcat_15_symbols_embossed_opac_int_0.geometry} material={materials.dod_chargersrthellcat_15_symbols_embossed_opac_int} />
            <mesh geometry={nodes.chassis_SUB4001_key_hole_002_int_0.geometry} material={materials.key_hole_002_int} />
            <mesh geometry={nodes.chassis_SUB5001_srt_001_0.geometry} material={materials.srt_001} />
            <mesh geometry={nodes.chassis_SUB6001_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.chassis_SUB6002_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB6003_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.chassis_SUB6004_stitch_009_glos_int_0.geometry} material={materials.stitch_009_glos_int} />
            <mesh geometry={nodes.chassis_SUB7001_INT_Plastic_0.geometry} material={materials.INT_Plastic} />
            <mesh geometry={nodes.chassis_SUB7002_INT_Plastic_0.geometry} material={materials.INT_Plastic} position={[0, -0.142, 0]} />
            <mesh geometry={nodes.chassis_SUB8001_INT_grill2_0.geometry} material={materials.INT_grill2} />
            <mesh geometry={nodes.chassis_SUB9001_INT_Rubber_0.geometry} material={materials.INT_Rubber} />
            <mesh geometry={nodes.sunroof_glass_ext001_Glass_0.geometry} material={materials.Glass} position={[0, 0, -0.002]} />
            <mesh geometry={nodes.sunroof_glass_int001_CAR_PAINT2_0.geometry} material={materials.CAR_PAINT2} />
            <mesh geometry={nodes.chassis_glass_int001_Glass_int_0.geometry} material={materials.Glass_int} />
            <mesh geometry={nodes.chassis_mirror001_Mirror_0.geometry} material={materials.Mirror} />
            <mesh geometry={nodes['chassis_screen001_tech-slide-5_lit_0'].geometry} material={materials['tech-slide-5_lit']} />
          </group>
        </group>
        <mesh geometry={nodes.BOLTS_LICENSEPL_Material001_0.geometry} material={materials['Material.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.CALIPER_FL_Hub_Plastic_0.geometry} material={materials.Hub_Plastic} position={[49.679, 37.335, 64.701]} rotation={[-Math.PI / 2, -0.059, 0]} scale={50.167} />
        <mesh geometry={nodes.CALIPER_FR_Hub_Plastic_0.geometry} material={materials.Hub_Plastic} position={[-49.69, 37.403, 64.652]} rotation={[-Math.PI / 2, 0.059, 0]} scale={[-50.167, 50.167, 50.167]} />
        <mesh geometry={nodes.CALIPER_RL_Hub_Plastic_0.geometry} material={materials.Hub_Plastic} position={[49.679, 36.788, -104.09]} rotation={[-Math.PI / 2, -0.059, 0]} scale={50.167} />
        <mesh geometry={nodes.CALIPER_RR_Hub_Plastic_0.geometry} material={materials.Hub_Plastic} position={[-49.69, 36.911, -104.09]} rotation={[-Math.PI / 2, 0.059, 0]} scale={[-50.167, 50.167, 50.167]} />
        <mesh geometry={nodes.DISK_FL_Brake_Disc002_0.geometry} material={materials['Brake_Disc.002']} position={[46.818, 36.623, 73.189]} rotation={[-Math.PI / 2, -0.06, 0]} scale={56.187} />
        <mesh geometry={nodes.DISK_RL_Brake_Disc002_0.geometry} material={materials['Brake_Disc.002']} position={[46.818, 36.075, -95.602]} rotation={[-Math.PI / 2, -0.06, 0]} scale={56.187} />
        <mesh geometry={nodes.GLASS_POL_Glass001_0.geometry} material={materials['Glass.001']} position={[-1.698, 98.183, -27.39]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.LICENSE_FRAME_licenseframeg2_0.geometry} material={materials.licenseframeg2} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_1_EXT_Plastic001_0.geometry} material={materials['EXT_Plastic.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_10_EXT_Plastic001_0.geometry} material={materials['EXT_Plastic.001']} position={[-1.165, 56.671, 122.117]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_11_vehiclelights128_0.geometry} material={materials.vehiclelights128} position={[14.004, 56.393, 122.191]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_12_EXT_Chrome001_0.geometry} material={materials['EXT_Chrome.001']} position={[-0.013, 99.431, -28.6]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_13_vehiclelights128_0.geometry} material={materials.vehiclelights128} position={[-15.551, 56.393, 121.952]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_14_EXT_Chrome001_0.geometry} material={materials['EXT_Chrome.001']} position={[-0.773, 56.651, 122.919]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_15_EXT_Plastic001_0.geometry} material={materials['EXT_Plastic.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_16_par_0.geometry} material={materials.material_88} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_17_par_0.geometry} material={materials.material_88} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_18_EXT_Plastic001_0.geometry} material={materials['EXT_Plastic.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_19_Glass001_0.geometry} material={materials['Glass.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_2_EXT_Chrome001_0.geometry} material={materials['EXT_Chrome.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_20_EXT_Plastic_Env_0.geometry} material={materials.EXT_Plastic_Env} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_21_EXT_Chrome001_0.geometry} material={materials['EXT_Chrome.001']} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_3_INT_Chrome001_0.geometry} material={materials['INT_Chrome.001']} position={[-0.102, 81.758, -38.134]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_4_Glass_int001_0.geometry} material={materials['Glass_int.001']} position={[14.754, 78.205, -37.726]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_6_INT_Plastic001_0.geometry} material={materials['INT_Plastic.001']} position={[-7.773, 74.878, -36.03]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_7_Glass001_0.geometry} material={materials['Glass.001']} position={[-0.774, 56.749, 123.132]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_8_EXT_Plastic_Env_0.geometry} material={materials.EXT_Plastic_Env} position={[-229.123, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.PART_9_black_solid_0.geometry} material={materials.black_solid} position={[0.052, 98.089, -29.393]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.POLICE_PART_EXT_Plastic001_0.geometry} material={materials['EXT_Plastic.001']} position={[0.024, 97.564, -28.455]} rotation={[-Math.PI / 2, 0, 0]} scale={50.167} />
        <mesh geometry={nodes.POL_LIGHTS_H_INT_Red_0.geometry} material={materials.INT_Red} position={[-459.981, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={177.637} />
        <mesh geometry={nodes.POL_LIGHTS_HAND_INT_Leather_0.geometry} material={materials.INT_Leather} position={[-459.981, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={177.637} />
        <mesh geometry={nodes.POL_LIGHTS_HAND2_INT_Chrome001_0.geometry} material={materials['INT_Chrome.001']} position={[-0.138, 14.556, -11.689]} rotation={[-Math.PI / 2, 0, 0]} scale={5568} />
        <mesh geometry={nodes.RIM_FL_Wheel_dinghyblack_0.geometry} material={materials.Wheel_dinghyblack} position={[53.858, 37.579, 72.766]} rotation={[-Math.PI / 2, -0.034, 0]} scale={50.167} />
        <mesh geometry={nodes.RIM_FR_Wheel_dinghyblack_0.geometry} material={materials.Wheel_dinghyblack} position={[-53.869, 37.647, 72.718]} rotation={[-Math.PI / 2, 0.036, 0]} scale={[-50.167, 50.167, 50.167]} />
        <mesh geometry={nodes.RIM_RL_Wheel_dinghyblack_0.geometry} material={materials.Wheel_dinghyblack} position={[53.858, 37.031, -96.025]} rotation={[-Math.PI / 2, -0.038, 0]} scale={50.167} />
        <mesh geometry={nodes.RIM_RR_Wheel_dinghyblack_0.geometry} material={materials.Wheel_dinghyblack} position={[-53.868, 37.18, -96.025]} rotation={[-Math.PI / 2, 0.035, 0]} scale={[-50.167, 50.167, 50.167]} />
        <mesh geometry={nodes.WHEEL_FL_dueleratnik001_0.geometry} material={materials['dueleratnik.001']} position={[48.413, 37.232, 72.982]} rotation={[-Math.PI / 2, -0.06, 0]} scale={56.187} />
        <mesh geometry={nodes.WHEEL_FR_dueleratnik001_0.geometry} material={materials['dueleratnik.001']} position={[48.413, 36.684, -95.809]} rotation={[-Math.PI / 2, -0.06, 0]} scale={56.187} />
        <mesh geometry={nodes.WHEEL_PART_FL_Wheel_Chrome_0.geometry} material={materials.Wheel_Chrome} position={[55.832, 37.656, 72.86]} rotation={[-Math.PI / 2, -0.06, 0]} scale={50.167} />
        <mesh geometry={nodes.WHEEL_PART_FR_Wheel_Chrome_0.geometry} material={materials.Wheel_Chrome} position={[-55.843, 37.724, 72.811]} rotation={[-Math.PI / 2, 0.059, 0]} scale={[-50.167, 50.167, 50.167]} />
        <mesh geometry={nodes.WHEEL_PART_RL_Wheel_Chrome_0.geometry} material={materials.Wheel_Chrome} position={[55.832, 37.109, -95.931]} rotation={[-Math.PI / 2, -0.06, 0]} scale={50.167} />
        <mesh geometry={nodes.WHEEL_PART_RR_Wheel_Chrome_0.geometry} material={materials.Wheel_Chrome} position={[-55.844, 37.207, -95.931]} rotation={[-Math.PI / 2, 0.06, 0]} scale={[-50.167, 50.167, 50.167]} />
        <mesh geometry={nodes.wheel_lf_SUB0003_Brake_Disc002_0.geometry} material={materials['Brake_Disc.002']} position={[-46.829, 36.69, 73.14]} rotation={[-Math.PI / 2, 0.06, 0]} scale={[-56.187, 56.187, 56.187]} />
        <mesh geometry={nodes.wheel_lf_SUB0004_Brake_Disc002_0.geometry} material={materials['Brake_Disc.002']} position={[-46.829, 36.198, -95.602]} rotation={[-Math.PI / 2, 0.06, 0]} scale={[-56.187, 56.187, 56.187]} />
        <mesh geometry={nodes.wheel_lf_SUB3003_dueleratnik001_0.geometry} material={materials['dueleratnik.001']} position={[-48.424, 37.299, 72.933]} rotation={[-Math.PI / 2, 0.06, 0]} scale={[-56.187, 56.187, 56.187]} />
        <mesh geometry={nodes.wheel_lf_SUB3004_dueleratnik001_0.geometry} material={materials['dueleratnik.001']} position={[-48.424, 36.808, -95.809]} rotation={[-Math.PI / 2, 0.06, 0]} scale={[-56.187, 56.187, 56.187]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cop.glb')
