query GetPost($id: Int!) {
  post(id: $id) {
    id
    title
    body
    userId
    createdAt
    updatedAt
    arrestLogId
    lat
    lon
    street
    city
    state
    zip
    category
    date_occurred
    postComments {
      id
      user {
        username
        role
      }
      body
      createdAt
      updatedAt
    }
    likes {
      id
      postId
      userId
      isActive
      createdAt
      updatedAt
    }
    arrestLog {
      id
      AGE
      ARREST_STATUS
      ArrestLocationAptFlr
      ArrestLocationCity
      ArrestLocationStreet
      ArrestLocationStreetNBR
      Arrest_Charge
      Arrest_ID
      Case_Number
      Charge_Description
      Charge_Sequence
      DATE_ARRESTED
      DOB
      Degree
      FIRSTNAME
      LASTNAME
      MIDDLENAME
      OBJECTID
      OBJECTID_1
      RACE
      SEX
      SUFFIX
      TIME_ARREST
      UNIQUEKEY
      createdAt
      updatedAt
    }
    user {
      id
      username
      role
    }
    imageUrls
  }
}

query GetPosts($data: PostsInput) {
  posts(data: $data) {
    status
    message
    data {
      data {
        id
        title
        body
        userId
        createdAt
        updatedAt
        arrestLogId
        imageUrls
        lat
        lon
        street
        city
        state
        zip
        category
        date_occurred
        user {
          id
          username
          role
        }
        postComments {
          id
          user {
            username
            role
          }
          body
          createdAt
          updatedAt
        }
        likes {
          id
          postId
          userId
          isActive
          createdAt
          updatedAt
        }
      }
      cursor
      hasNextPage
    }
  }
}

query GetMapPosts {
  mapPosts {
    status
    message
    data {
      id
      lat
      lon
      title
      date_occurred
    }
  }
}

mutation CreatePost($data: CreatePostInput!) {
  createPost(data: $data) {
    id
  }
}

mutation UpdatePost($id: Int!, $data: UpdatePostInput!) {
  updatePost(id: $id, data: $data) {
    id
  }
}

mutation DeletePost($id: Int!) {
  deletePost(id: $id) {
    id
  }
}

mutation CreatePostComment($data: CreatePostCommentInput!) {
  createPostComment(data: $data) {
    id
    postId
    body
    createdAt
    updatedAt
  }
}
