# graphql/queries/getUser.graphql
# query GetUser($id: ID!) {
#   user(id: $id) {
#     id
#     firstname
#     lastname
#     email
#     username
#     password
#     role
#     createdAt
#     updatedAt
#   }
# }

query GetUserComments($id: ID!, $data: PostCommentInput) {
  user(id: $id) {
    status
    message
    data {
      id
      comments(data: $data) {
        data {
          data {
            id
            body
            createdAt
            updatedAt
            post {
              title
              category
            }
          }
          hasNextPage
          cursor
        }
      }
    }
  }
}

query GetUserLikedPosts($id: ID!, $data: LikedPostInput) {
  user(id: $id) {
    status
    message
    data {
      id
      likedPosts(data: $data) {
        data {
          data {
            id
            post {
              id
              title
              body
              userId
              createdAt
              updatedAt
              arrestLogId
              lat
              lon
              street
              city
              state
              zip
              category
              date_occurred
              postComments {
                id
                user {
                  username
                  role
                }
                body
                createdAt
                updatedAt
              }
              likes {
                id
                postId
                userId
                isActive
                createdAt
                updatedAt
              }
              arrestLog {
                id
                AGE
                ARREST_STATUS
                ArrestLocationAptFlr
                ArrestLocationCity
                ArrestLocationStreet
                ArrestLocationStreetNBR
                Arrest_Charge
                Arrest_ID
                Case_Number
                Charge_Description
                Charge_Sequence
                DATE_ARRESTED
                DOB
                Degree
                FIRSTNAME
                LASTNAME
                MIDDLENAME
                OBJECTID
                OBJECTID_1
                RACE
                SEX
                SUFFIX
                TIME_ARREST
                UNIQUEKEY
                createdAt
                updatedAt
              }
              user {
                id
                username
                role
              }
              imageUrls
            }
          }
          cursor
          hasNextPage
        }
        status
        message
      }
    }
  }
}

query GetUserPosts($id: ID!, $data: PostsInput) {
  user(id: $id) {
    status
    message
    data {
      id
      posts(data: $data) {
        data {
          data {
            id
            title
            body
            userId
            createdAt
            updatedAt
            arrestLogId
            lat
            lon
            street
            city
            state
            zip
            category
            date_occurred
            postComments {
              id
              user {
                username
                role
              }
              body
              createdAt
              updatedAt
            }
            likes {
              id
              postId
              userId
              isActive
              createdAt
              updatedAt
            }
            arrestLog {
              id
              AGE
              ARREST_STATUS
              ArrestLocationAptFlr
              ArrestLocationCity
              ArrestLocationStreet
              ArrestLocationStreetNBR
              Arrest_Charge
              Arrest_ID
              Case_Number
              Charge_Description
              Charge_Sequence
              DATE_ARRESTED
              DOB
              Degree
              FIRSTNAME
              LASTNAME
              MIDDLENAME
              OBJECTID
              OBJECTID_1
              RACE
              SEX
              SUFFIX
              TIME_ARREST
              UNIQUEKEY
              createdAt
              updatedAt
            }
            user {
              id
              username
              role
            }
            imageUrls
          }
          hasNextPage
          cursor
        }
      }
    }
  }
}

query GetUsers {
  users {
    data {
      id
      firstname
      lastname
      email
      username
      role
      createdAt
      updatedAt
    }
    status
    message
  }
}

query Me {
  me {
    id
    firstname
    lastname
    email
    username
    role
    createdAt
    updatedAt
  }
}

mutation registerUser($data: CreateUserInput!) {
  registerUser(data: $data) {
    data {
      firstname
      lastname
      email
    }
    status
    message
  }
}

mutation verifyEmail($token: Token!) {
  verifyEmail(token: $token)
}

mutation resendVerificationEmail($email: String!) {
  resendVerificationEmail(email: $email)
}

mutation UpsertUser($data: UpsertUserInput!) {
  upsertUser(data: $data) {
    data {
      user {
        firstname
        lastname
        email
      }
      token
      refreshToken
    }
    status
    message
  }
}

mutation UpdateUser($id: ID!, $data: UpdateUserInput!) {
  updateUser(id: $id, data: $data) {
    id
    firstname
    lastname
    email
    username
    createdAt
    updatedAt
  }
}

mutation DeleteUser($id: ID!) {
  deleteUser(id: $id) {
    id
    firstname
    lastname
    email
    username
    role
    createdAt
    updatedAt
  }
}

mutation login($data: LoginInput!) {
  login(data: $data) {
    user {
      id
      firstname
      lastname
      email
      username
      role
      emailVerified
      createdAt
      updatedAt
    }
    accessToken
  }
}

mutation logout {
  logout
}

mutation loginGuest {
  loginGuest {
    token
  }
}
